[mongodb]
mongodb.devaws84s.online

[catalogue]
catalogue.devaws84s.online

[redis]
redis.devaws84s.online

[user]
user.devaws84s.online

[cart]
cart.devaws84s.online

[frontend]
frontend.devaws84s.online

[mysql]
mysql.devaws84s.online

[payment]
payment.devaws84s.online

[rabbitmq]
rabbitmq.devaws84s.online

[shipping]
shipping.devaws84s.online

[dispatch]
dispatch.devaws84s.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321